### ISSUE TITLE
when importing the main routes components in the App.tsx make sure to use Lazy function from "react" for better performance.

### ISSUE THREAD

**Issue by Machoudi2002** [terfiel-22/terfiel-blog-react#1]
Using the React Lazy function is a great way to improve the performance of your React application by implementing code-splitting. Code-splitting allows you to load only the necessary components when they are actually needed, reducing the initial load time and improving the overall user experience.

**Comment by terfiel-22** [comment]
Thanks for the suggestion sir. I'll surely apply that.
